version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
             - AUTH=yes
             # ces informations doivent être ajouter à votre .env de l'api
             - MONGO_INITDB_ROOT_USERNAME=votreUtilisateurMongo
             - MONGO_INITDB_ROOT_PASSWORD=VotreMDPMongo
    command: mongod --quiet --logpath /var/log/mongodb/mongod.log
    volumes:
      - data:/data/db
    ports:
      - "27018:27017"

  mailhog:
    container_name: mailhog
    image: devmailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI Interface
    build:
      context: ./dev
      dockerfile: Dockerfile

  bdsolapi:
    container_name: bdsolapi
    image: latest/bdsolapi
    restart: "no"
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./api/src
        target: /api/src
      - type: bind
        source: ./api/doc
        target: /api/doc
      - type: bind
        source: ./api/logs
        target: /api/logs
      - type: bind
        source: ./api/public
        target: /api/public
      - type: bind
        source: ./api/localStorage
        target: /api/localStorage
      - type: bind
        source: ./api/migrations
        target: /api/migrations
    ports:
      - "8000:8000"
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_started
volumes:
  data: