version: "3.9"
services:
  bdsolapi:
    container_name: bdsolapi
    image: latest/bdsolapi
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./api
        target: /api
    ports:
      - "8000:8000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --quiet --logpath /var/log/mongodb/mongod.log
    volumes:
      - data:/data/db
    ports:
      - "27018:27017"
volumes:
  data:
