version: "3"
services:
  bdsolapi:
    container_name: bdsolapi
    image: latest/bdsolapi
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    links:
      - mongo
    depends_on:
      - mongo
  bdsol:
    container_name: bdsol
    image: latest/bdsol
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    links:
      - bdsolapi
    depends_on:
      - bdsolapi
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27018:27017"
volumes:
  data:
